import { z } from "zod";

const optionalEmail = z.union([z.email(), z.literal("")]).optional();
const optionalUrl = z.union([z.url(), z.literal("")]).optional();
const optionalNumber = z.preprocess(
  (value) => value === "" || value === null || value === undefined ? undefined : value,
  z.coerce.number().nonnegative().optional(),
);
const requiredNumber = z.preprocess(
  (value) => value === "" || value === null || value === undefined ? undefined : value,
  z.coerce.number().nonnegative(),
);
const optionalDateString = z.preprocess(
  (value) => value === "" || value === null || value === undefined ? undefined : value,
  z.string().optional(),
);
const optionalEnum = <T extends [string, ...string[]]>(values: T) => z.preprocess(
  (value) => value === "" || value === null || value === undefined ? undefined : value,
  z.enum(values).optional(),
);
const tagString = z.preprocess(
  (value) => {
    if (Array.isArray(value)) {
      return value;
    }

    if (typeof value !== "string") {
      return [];
    }

    return value
      .split(",")
      .map((tag) => tag.trim())
      .filter(Boolean);
  },
  z.array(z.string()),
);

export const leadSchema = z.object({
  fullName: z.string().min(2, "Full name is required."),
  phoneNumber: z.string().min(7, "A valid phone number is required."),
  whatsappNumber: z.string().optional(),
  email: optionalEmail,
  contactPreference: z.string().optional(),
  preferredLocation: z.string().optional(),
  preferredState: z.string().optional(),
  preferredCity: z.string().optional(),
  geoAddress: z.string().optional(),
  geoLatitude: z.preprocess(
    (value) => value === "" || value === null || value === undefined ? undefined : value,
    z.coerce.number().min(-90).max(90).optional(),
  ),
  geoLongitude: z.preprocess(
    (value) => value === "" || value === null || value === undefined ? undefined : value,
    z.coerce.number().min(-180).max(180).optional(),
  ),
  geoAccuracy: optionalNumber,
  geoCapturedAt: optionalDateString,
  propertyType: z.string().optional(),
  preferredPropertyCategory: z.string().optional(),
  preferredBedrooms: optionalNumber,
  budgetMinimum: optionalNumber,
  budgetMaximum: optionalNumber,
  preferredBudgetCurrency: z.string().optional(),
  interestCategory: optionalEnum(["solar", "buildingMaterials", "generalServices", "custom"]),
  transactionInterest: optionalEnum(["buy", "rent", "lease", "invest"]),
  propertyId: z.string().optional(),
  propertyName: z.string().optional(),
  propertyReferenceNumber: z.string().optional(),
  unitId: z.string().optional(),
  unitName: z.string().optional(),
  offeringId: z.string().optional(),
  offeringName: z.string().optional(),
  offeringReferenceNumber: z.string().optional(),
  offeringType: optionalEnum(["property", "unit", "material", "solarEquipment", "solarService", "installationProject", "consultancy", "maintenance", "service", "other"]),
  offeringVertical: optionalEnum(["realEstate", "solar", "buildingMaterials", "generalServices", "custom"]),
  intendedUse: z.string().optional(),
  paymentPreference: z.string().optional(),
  preferredInspectionDate: optionalDateString,
  source: z.string().min(2, "Lead source is required."),
  sourcePlatform: z.string().optional(),
  campaignName: z.string().optional(),
  sourceReference: z.string().optional(),
  referralName: z.string().optional(),
  referralPhone: z.string().optional(),
  assignedTo: z.string().optional(),
  assignedAgentId: z.string().optional(),
  score: z.coerce.number().min(0).max(100).default(25),
  leadTemperature: optionalEnum(["cold", "warm", "hot"]),
  status: z.enum([
    "new",
    "contacted",
    "qualified",
    "propertyRecommended",
    "inspectionScheduled",
    "inspectionCompleted",
    "negotiation",
    "offerMade",
    "paymentPending",
    "converted",
    "lost",
    "dormant",
  ]),
  tags: tagString.default([]),
  notes: z.string().optional(),
  nextFollowUpAt: optionalDateString,
  lostReason: z.string().optional(),
});

export const clientSchema = z.object({
  clientType: z.enum(["individual", "corporate"]),
  category: z.string().min(2, "Client category is required."),
  fullName: z.string().min(2, "Client name is required."),
  companyName: z.string().optional(),
  phoneNumber: z.string().min(7, "A valid phone number is required."),
  whatsappNumber: z.string().optional(),
  email: optionalEmail,
  address: z.string().optional(),
  occupation: z.string().optional(),
  employer: z.string().optional(),
  identificationType: z.string().optional(),
  identificationNumber: z.string().optional(),
  taxIdentificationNumber: z.string().optional(),
  nextOfKinName: z.string().optional(),
  nextOfKinPhone: z.string().optional(),
  preferredCommunicationMethod: z.string().optional(),
  assignedRelationshipManager: z.string().optional(),
  status: z.string().default("active"),
  tags: tagString.default([]),
  notes: z.string().optional(),
});

const dealQuoteLineSchema = z.object({
  id: z.string().min(1),
  lineType: z.enum(["inventoryProduct", "externalMaterial", "service", "labour", "transport", "other"]),
  fulfillment: z.enum(["checkStock", "procureToStock", "directToSite", "service"]),
  offeringId: z.string().optional(),
  offeringName: z.string().optional(),
  offeringType: optionalEnum(["property", "unit", "material", "solarEquipment", "solarService", "installationProject", "consultancy", "maintenance", "service", "other"]),
  description: z.string().min(1),
  sku: z.string().optional(),
  brandId: z.string().optional(),
  brandName: z.string().optional(),
  quantity: z.number().positive(),
  unitOfMeasure: z.string().optional(),
  unitPrice: z.number().min(0),
  discountAmount: z.number().min(0),
  taxRate: z.number().min(0).max(100),
  estimatedUnitCost: z.number().min(0),
  subtotal: z.number().min(0),
  taxAmount: z.number().min(0),
  totalAmount: z.number().min(0),
});

export const dealSchema = z.object({
  title: z.string().min(2, "Deal title is required."),
  dealType: z.enum(["sale", "rent", "lease", "reservation", "investment", "other"]),
  dealCategory: optionalEnum(["solar", "buildingMaterials", "generalServices", "custom"]),
  leadId: z.string().optional(),
  leadName: z.string().optional(),
  clientId: z.string().optional(),
  clientName: z.string().optional(),
  clientPhone: z.string().optional(),
  clientEmail: optionalEmail,
  propertyId: z.string().optional(),
  propertyName: z.string().optional(),
  propertyReferenceNumber: z.string().optional(),
  unitId: z.string().optional(),
  unitName: z.string().optional(),
  offeringId: z.string().optional(),
  offeringName: z.string().optional(),
  offeringReferenceNumber: z.string().optional(),
  offeringType: optionalEnum(["property", "unit", "material", "solarEquipment", "solarService", "installationProject", "consultancy", "maintenance", "service", "other"]),
  offeringVertical: optionalEnum(["realEstate", "solar", "buildingMaterials", "generalServices", "custom"]),
  offeringQuantity: optionalNumber,
  offeringUnitPrice: optionalNumber,
  quoteSubtotal: optionalNumber,
  quoteDiscountAmount: optionalNumber,
  quoteTaxAmount: optionalNumber,
  quoteTotal: optionalNumber,
  quoteEstimatedCost: optionalNumber,
  quoteLines: z.array(dealQuoteLineSchema).optional(),
  proposalStatus: optionalEnum(["notStarted", "drafting", "sent", "accepted", "rejected", "expired"]),
  fulfillmentStatus: optionalEnum(["notStarted", "awaitingPayment", "procurement", "scheduled", "inProgress", "delivered", "completed", "onHold", "cancelled"]),
  fulfillmentDueDate: optionalDateString,
  scopeOfWork: z.string().optional(),
  deliveryNotes: z.string().optional(),
  dealOwnerId: z.string().optional(),
  dealOwnerName: z.string().optional(),
  dealOwnerEmail: z.string().optional(),
  offerAmount: optionalNumber,
  agreedAmount: optionalNumber,
  reservationAmount: optionalNumber,
  depositAmount: optionalNumber,
  expectedCloseDate: optionalDateString,
  closeProbability: z.preprocess(
    (value) => value === "" || value === null || value === undefined ? undefined : value,
    z.coerce.number().min(0).max(100).optional(),
  ),
  paymentPlan: z.string().optional(),
  financeStatus: optionalEnum(["notInvoiced", "paymentPending", "partPaid", "paid", "overdue"]),
  legalStatus: optionalEnum(["notStarted", "drafting", "inReview", "signed", "completed", "blocked"]),
  commissionType: optionalEnum(["percentage", "fixed", "none"]),
  commissionValue: optionalNumber,
  commissionAmount: optionalNumber,
  status: z.enum([
    "new",
    "qualified",
    "propertyRecommended",
    "inspectionScheduled",
    "inspectionCompleted",
    "negotiation",
    "offerMade",
    "paymentPending",
    "won",
    "lost",
    "dormant",
  ]),
  lostReason: z.string().optional(),
  notes: z.string().optional(),
});

export const propertySchema = z.object({
  name: z.string().min(2, "Property name is required."),
  category: z.string().min(2, "Category is required."),
  brandId: z.string().optional(),
  brandName: z.string().optional(),
  transactionTypes: tagString,
  description: z.string().optional(),
  address: z.string().min(5, "Address is required."),
  state: z.string().min(2, "State is required."),
  localGovernmentArea: z.string().optional(),
  city: z.string().min(2, "City is required."),
  estateOrNeighborhood: z.string().optional(),
  propertyOwnerId: z.string().optional(),
  developerId: z.string().optional(),
  managementCompanyId: z.string().optional(),
  developerName: z.string().optional(),
  assignedManager: z.string().optional(),
  listingStatus: z.enum(["listed", "draft", "private", "offMarket"]).default("listed"),
  propertyStatus: z.enum(["draft", "available", "reserved", "underNegotiation", "sold", "rented", "leased", "occupied", "vacant", "underMaintenance", "unavailable", "withdrawn"]),
  marketingStatus: z.enum(["active", "paused", "needsMedia", "comingSoon", "archived"]).default("active"),
  askingPrice: optionalNumber,
  minimumAcceptablePrice: optionalNumber,
  rentAmount: optionalNumber,
  serviceCharge: optionalNumber,
  cautionFee: optionalNumber,
  legalFee: optionalNumber,
  agencyFeeType: z.string().optional(),
  agencyFeeValue: optionalNumber,
  agencyFee: optionalNumber,
  commissionType: z.string().optional(),
  commissionValue: optionalNumber,
  commissionAmount: optionalNumber,
  features: tagString.default([]),
  latitude: optionalNumber,
  longitude: optionalNumber,
  size: optionalNumber,
  sizeUnit: z.string().optional(),
  bedrooms: optionalNumber,
  bathrooms: optionalNumber,
  toilets: optionalNumber,
  parkingSpaces: optionalNumber,
  floors: optionalNumber,
  unitsCount: optionalNumber,
  furnishingStatus: z.string().optional(),
  landmark: z.string().optional(),
  dateListed: optionalDateString,
  availabilityDate: optionalDateString,
  titleType: z.string().optional(),
  titleStatus: z.string().optional(),
  surveyPlanNumber: z.string().optional(),
  registrationNumber: z.string().optional(),
  legalNotes: z.string().optional(),
  virtualTourUrl: optionalUrl,
  brochureUrl: optionalUrl,
  mediaFolderUrl: optionalUrl,
  inspectionNotes: z.string().optional(),
});

export const offeringSchema = z.object({
  name: z.string().min(2, "Product/service name is required."),
  vertical: z.enum(["solar", "buildingMaterials", "generalServices", "custom"]),
  type: z.enum(["property", "unit", "material", "solarEquipment", "solarService", "installationProject", "consultancy", "maintenance", "service", "other"]),
  category: z.string().min(2, "Category is required."),
  brandId: z.string().optional(),
  brandName: z.string().optional(),
  description: z.string().optional(),
  sku: z.string().optional(),
  barcode: z.string().optional(),
  trackingMode: z.enum(["none", "batch", "serial"]).optional(),
  unitOfMeasure: z.string().optional(),
  sellingPrice: optionalNumber,
  costPrice: optionalNumber,
  reorderLevel: optionalNumber,
  supplierName: z.string().optional(),
  serviceDurationDays: optionalNumber,
  tags: tagString.default([]),
  notes: z.string().optional(),
  status: z.enum(["active", "draft", "inactive", "archived"]),
}).superRefine((value, context) => {
  if (["material", "solarEquipment"].includes(value.type) && !value.brandId?.trim()) {
    context.addIssue({ code: "custom", message: "Select a brand for this inventory product.", path: ["brandId"] });
  }
});

export const unitSchema = z.object({
  propertyId: z.string().min(2, "Property is required."),
  propertyName: z.string().optional(),
  propertyReferenceNumber: z.string().optional(),
  phase: z.string().optional(),
  block: z.string().optional(),
  floor: z.string().optional(),
  plotNumber: z.string().optional(),
  unitNumber: z.string().min(1, "Unit number is required."),
  unitType: z.string().optional(),
  size: optionalNumber,
  sizeUnit: z.string().optional(),
  bedrooms: optionalNumber,
  bathrooms: optionalNumber,
  toilets: optionalNumber,
  parkingSpaces: optionalNumber,
  furnishingStatus: z.string().optional(),
  features: tagString.default([]),
  askingPrice: optionalNumber,
  rentAmount: optionalNumber,
  serviceCharge: optionalNumber,
  cautionFee: optionalNumber,
  legalFee: optionalNumber,
  availabilityDate: optionalDateString,
  reservationExpiresAt: optionalDateString,
  notes: z.string().optional(),
  status: z.enum(["draft", "available", "reserved", "underNegotiation", "sold", "rented", "leased", "occupied", "vacant", "underMaintenance", "unavailable", "withdrawn"]),
});

export const rentalTenancySchema = z.object({
  tenantClientId: z.string().min(2, "Tenant/client is required."),
  tenantName: z.string().optional(),
  tenantEmail: z.string().optional(),
  tenantPhone: z.string().optional(),
  propertyId: z.string().min(2, "Property is required."),
  propertyName: z.string().optional(),
  unitId: z.string().optional(),
  unitName: z.string().optional(),
  landlordOwnerId: z.string().optional(),
  landlordOwnerName: z.string().optional(),
  leaseStartDate: optionalDateString,
  leaseEndDate: optionalDateString,
  moveInDate: optionalDateString,
  moveOutDate: optionalDateString,
  rentAmount: requiredNumber,
  paymentCycle: z.enum(["monthly", "quarterly", "biannual", "annual", "oneOff"]),
  rentDueDay: optionalNumber,
  gracePeriodDays: optionalNumber,
  serviceCharge: optionalNumber,
  cautionFee: optionalNumber,
  agencyFee: optionalNumber,
  legalFee: optionalNumber,
  totalInitialPayment: optionalNumber,
  paymentStatus: optionalEnum(["notInvoiced", "invoiced", "partPaid", "paid", "overdue"]),
  renewalNoticeDate: optionalDateString,
  nextRentDueDate: optionalDateString,
  agreementStatus: optionalEnum(["notStarted", "drafting", "sent", "signed", "expired"]),
  status: z.enum(["draft", "active", "expiringSoon", "renewalDue", "renewed", "terminated", "defaulting", "movedOut"]),
  notes: z.string().optional(),
});

export const developmentProjectSchema = z.object({
  name: z.string().min(2, "Project name is required."),
  projectType: z.string().min(2, "Project type is required."),
  propertyId: z.string().optional(),
  propertyName: z.string().optional(),
  propertyReferenceNumber: z.string().optional(),
  location: z.string().optional(),
  state: z.string().optional(),
  city: z.string().optional(),
  projectManagerId: z.string().optional(),
  projectManagerName: z.string().optional(),
  projectManagerEmail: z.string().optional(),
  contractorName: z.string().optional(),
  contractorPhone: z.string().optional(),
  contractorEmail: optionalEmail,
  currentPhase: z.string().optional(),
  permitStatus: optionalEnum(["notStarted", "inReview", "approved", "rejected", "notRequired"]),
  startDate: optionalDateString,
  expectedCompletionDate: optionalDateString,
  actualCompletionDate: optionalDateString,
  budget: optionalNumber,
  amountSpent: optionalNumber,
  progressPercent: z.preprocess(
    (value) => value === "" || value === null || value === undefined ? undefined : value,
    z.coerce.number().min(0).max(100).optional(),
  ),
  riskLevel: optionalEnum(["low", "medium", "high", "critical"]),
  priority: optionalEnum(["low", "medium", "high", "urgent"]),
  status: z.enum(["concept", "planning", "approval", "procurement", "construction", "inspection", "handover", "completed", "onHold", "cancelled"]),
  notes: z.string().optional(),
});

export const marketingCampaignSchema = z.object({
  name: z.string().min(2, "Campaign name is required."),
  campaignType: z.string().min(2, "Campaign type is required."),
  channel: z.enum(["Facebook", "Instagram", "Google Ads", "WhatsApp", "Email", "SMS", "Property portal", "Referral", "Event", "Outdoor", "Other"]),
  objective: z.string().optional(),
  propertyId: z.string().optional(),
  propertyName: z.string().optional(),
  propertyReferenceNumber: z.string().optional(),
  campaignManagerId: z.string().optional(),
  campaignManagerName: z.string().optional(),
  campaignManagerEmail: z.string().optional(),
  targetAudience: z.string().optional(),
  targetLocation: z.string().optional(),
  sourceTag: z.string().optional(),
  landingPageUrl: optionalUrl,
  startDate: optionalDateString,
  endDate: optionalDateString,
  budget: optionalNumber,
  amountSpent: optionalNumber,
  expectedLeads: optionalNumber,
  actualLeads: optionalNumber,
  qualifiedLeads: optionalNumber,
  convertedLeads: optionalNumber,
  priority: optionalEnum(["low", "medium", "high", "urgent"]),
  status: z.enum(["draft", "planned", "active", "paused", "completed", "cancelled"]),
  notes: z.string().optional(),
});

export const taskSchema = z.object({
  title: z.string().min(2, "Task title is required."),
  description: z.string().optional(),
  dueAt: optionalDateString,
  estimatedDurationMinutes: optionalNumber,
  expectedOutcome: z.string().optional(),
  location: z.string().optional(),
  priority: z.enum(["low", "medium", "high", "urgent"]),
  reminderMinutesBefore: optionalNumber,
  status: z.enum(["notStarted", "inProgress", "waiting", "completed", "cancelled", "overdue"]),
  assignedTo: z.string().optional(),
  assignedToEmail: z.string().optional(),
  assignedToName: z.string().optional(),
  relatedEntityType: optionalEnum(["deal", "lead", "client", "property", "unit", "tenancy", "development", "installationProject", "marketing", "offering"]),
  relatedEntityId: z.string().optional(),
});

export const activitySchema = z.object({
  type: z.enum(["phoneCall", "whatsappMessage", "email", "sms", "meeting", "inspection", "followUp", "documentRequest", "paymentReminder", "complaint", "internalNote"]),
  subject: z.string().min(2, "Subject is required."),
  body: z.string().optional(),
  status: z.string().optional(),
  relatedEntityType: optionalEnum(["deal", "lead", "client", "property", "unit", "task", "tenancy", "development", "installationProject", "marketing", "offering"]),
  relatedEntityId: z.string().optional(),
});
